live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 3

[window.padding]
x = 10
y = 10
